# --- Core Application ---
spring.application.name=travel-app
server.port=8080

# --- Security ---
application.security.jwt.secret-key=${JWT_SECRET}

# --- External APIs ---
restcountries.api.base-url=https://api.restcountries.com/countries/v5/name
restcountries.api.key=${REST_COUNTRIES_API_KEY}

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true